REM Only known msx models with internal disk drive
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Al_Alamiah_AX370
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Canon_V-30F
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Daewoo_CPC-400S
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Hitachi_MB-H70
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Mitsubishi_ML-G30_model_1
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Mitsubishi_ML-G30_model_2
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Mitsubishi_ML-G3_ES
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine National_FS-4600F
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine National_FS-4700F
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine National_FS-5000F2
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine National_FS-5500F1
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine National_FS-5500F2
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Panasonic_FS-A1F
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Panasonic_FS-A1FM
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Panasonic_FS-A1FX
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Panasonic_FS-A1GT
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Panasonic_FS-A1ST
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Panasonic_FS-A1WSX
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Panasonic_FS-A1WX
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Philips_NMS_8245
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Philips_NMS_8250-16
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Philips_NMS_8250-19
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Philips_NMS_8250
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Philips_NMS_8255
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Philips_VG_8230
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Philips_VG_8235-00
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Philips_VG_8235-20
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Philips_VG_8235-39
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Pioneer_UC-V102
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Sanyo_MPC-25FD
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Sanyo_MPC-25FS
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Sanyo_PHC-70FD
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Sanyo_PHC-70FD2
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Sanyo_PHC-77
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Sony_HB-F1XD
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Sony_HB-F1XDJ
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Sony_HB-F1XDmk2
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Sony_HB-F1XV
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Sony_HB-F500
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Sony_HB-F500P
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Sony_HB-F500_v2
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Sony_HB-F700D
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Sony_HB-F700F
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Sony_HB-F700P
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Sony_HB-F700S
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Sony_HB-F900
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Sony_HB-G900AP
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Sony_HB-G900D
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Sony_HB-G900P
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Sony_HB-T600
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Spectravideo_SVI-738
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Toshiba_HX-34
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Victor_HC-90A
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Victor_HC-95A
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Yamaha_AX350
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Yamaha_AX350II
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Yamaha_AX350IIF
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Yamaha_AX500
C:\tools\openmsx20\openmsx.exe -cart rom/ndrives.rom  -script openmsx_scr_exit.tcl -machine Yamaha_YIS-805-128R2